-- AlterTable
ALTER TABLE "SeatingMap" ADD COLUMN     "roomHeight" INTEGER,
ADD COLUMN     "roomWidth" INTEGER,
ADD COLUMN     "unit" TEXT NOT NULL DEFAULT 'ft',
ALTER COLUMN "imageUrl" DROP NOT NULL;

-- AlterTable
ALTER TABLE "SeatingPin" ADD COLUMN     "color" TEXT,
ADD COLUMN     "h" DOUBLE PRECISION NOT NULL DEFAULT 0.09,
ADD COLUMN     "kind" TEXT NOT NULL DEFAULT 'table',
ADD COLUMN     "rotation" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "seats" INTEGER,
ADD COLUMN     "shape" TEXT NOT NULL DEFAULT 'circle',
ADD COLUMN     "w" DOUBLE PRECISION NOT NULL DEFAULT 0.09;
